creation_rules:
  - age: "age1p0szngmeuyegrjv74k6ejxqua53jxqxners7fxgzffz54cm9eclsrw7tyr,age14jhl3c6s5mj5dux7e25r9zchsrgydmhvgu62h7ywsklgheslayqqd8kwnt"
    pgp: "3DCEEA9B83940FF80EABBFEB599A85D29920C69C"
