version: "3"

name: vaultwarden-container

services:
  bitwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DOMAIN
      - ADMIN_TOKEN
    volumes:
      - ./vw-data:/data
    ports:
      - 8950:80
      - 3012:3012
