# Auto-generated using compose2nix v0.1.9.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "docker.io/vaultwarden/server:latest";
    environment = {
      SIGNUPS_ALLOWED = "false";
      SMTP_PORT = "465";
      SMTP_SECURITY = "force_tls";
      WEBSOCKET_ENABLED = "true";
    };
    volumes = [
      "vw-data:/data:rw"
    ];
    ports = [
      "8950:80/tcp"
      "3012:3012/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=bitwarden"
      "--network=vaultwarden-container_default"
    ];
  };
  systemd.services."podman-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-vaultwarden-container_default.service"
    ];
    requires = [
      "podman-network-vaultwarden-container_default.service"
    ];
    partOf = [
      "podman-compose-vaultwarden-container-root.target"
    ];
    wantedBy = [
      "podman-compose-vaultwarden-container-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-vaultwarden-container_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.podman}/bin/podman network rm -f vaultwarden-container_default";
    };
    script = ''
      podman network inspect vaultwarden-container_default || podman network create vaultwarden-container_default
    '';
    partOf = [ "podman-compose-vaultwarden-container-root.target" ];
    wantedBy = [ "podman-compose-vaultwarden-container-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-vaultwarden-container-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
