# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."shoko_server" = {
    image = "ghcr.io/shokoanime/server:latest";
    volumes = [
      "/media/Anime:/mnt/anime:rw"
      "/mnt/alldebrid:/mnt/alldebrid:rw"
      "shoko_shoko-config:/home/shoko/.shoko:rw"
    ];
    ports = [
      "8111:8111/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=shoko_server"
      "--network=shoko_default"
      "--shm-size=268435456"
    ];
  };
  systemd.services."podman-shoko_server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "s3fs_media.service"
      "alldebrid_mount.service"
      "podman-network-shoko_default.service"
      "podman-volume-shoko_shoko-config.service"
    ];
    requires = [
      "podman-network-shoko_default.service"
      "podman-volume-shoko_shoko-config.service"
    ];
    partOf = [
      "podman-compose-shoko-root.target"
    ];
    wantedBy = [
      "podman-compose-shoko-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-shoko_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f shoko_default";
    };
    script = ''
      podman network inspect shoko_default || podman network create shoko_default
    '';
    partOf = ["podman-compose-shoko-root.target"];
    wantedBy = ["podman-compose-shoko-root.target"];
  };

  # Volumes
  systemd.services."podman-volume-shoko_shoko-config" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect shoko_shoko-config || podman volume create shoko_shoko-config
    '';
    partOf = ["podman-compose-shoko-root.target"];
    wantedBy = ["podman-compose-shoko-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-shoko-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
