# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."rdtclient" = {
    image = "rogerfar/rdtclient";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/London";
    };
    volumes = [
      "/mnt/alldebrid:/mnt/alldebrid:rw"
      "/mnt/rdt-download:/mnt/rdt-download:rw"
      "rdt-client_rdt-client-data:/data/db:rw"
    ];
    dependsOn = [
      "gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-rdtclient" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-volume-rdt-client_rdt-client-data.service"
    ];
    requires = [
      "podman-volume-rdt-client_rdt-client-data.service"
    ];
    partOf = [
      "podman-compose-rdt-client-root.target"
    ];
    wantedBy = [
      "podman-compose-rdt-client-root.target"
    ];
  };

  # Volumes
  systemd.services."podman-volume-rdt-client_rdt-client-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect rdt-client_rdt-client-data || podman volume create rdt-client_rdt-client-data
    '';
    partOf = [ "podman-compose-rdt-client-root.target" ];
    wantedBy = [ "podman-compose-rdt-client-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-rdt-client-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
