---
version: "3.3"
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - rdt-client-data:/data/db
      - /var/rdt-download:/var/rdt-download
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped
    network_mode: "container:gluetun"
volumes:
  rdt-client-data:
