---
version: "3.3"
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - rdt-client-data:/data/db
      - /mnt/alldebrid:/mnt/alldebrid
      - /mnt/rdt-download:/mnt/rdt-download
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped
volumes:
  rdt-client-data:
