---
version: "3.8"

name: foundry-container

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry.fuzzle.uk
    volumes:
      - foundry-data:/data
    environment:
      - FOUNDRY_LICENSE_URL
      - FOUNDRY_LICENSE_KEY
      - FOUNDRY_ADMIN_KEY
      - FOUNDRY_USERNAME
      - FOUNDRY_PASSWORD
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    user: 421:421
volumes:
  foundry-data:
