---
version: "3.8"

name: foundry-container

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry.fuzzle.uk
    volumes:
      - foundry-data:/data
      - /run/secrets/foundry-aws:/run/aws.json
    environment:
      - FOUNDRY_LICENSE_URL
      - FOUNDRY_LICENSE_KEY
      - FOUNDRY_ADMIN_KEY
      - FOUNDRY_USERNAME
      - FOUNDRY_PASSWORD
      - FOUNDRY_AWS_CONFIG=/run/aws.json
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    user: 421:421
  foundry2:
    image: felddy/foundryvtt:release
    hostname: foundry-baylok.fuzzle.uk
    volumes:
      - baylok-data:/data
      - /run/secrets/foundry-aws:/run/aws.json
    environment:
      - FOUNDRY_LICENSE_URL
      - FOUNDRY_LICENSE_KEY
      - FOUNDRY_ADMIN_KEY
      - FOUNDRY_USERNAME
      - FOUNDRY_PASSWORD
      - FOUNDRY_AWS_CONFIG=/run/aws.json
    ports:
      - target: 30000
        published: 30001
        protocol: tcp
    user: 421:421
volumes:
  foundry-data:
  baylok-data:
