version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP Proxy
      - 6500:6500/tcp # rdt-client
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - SERVER_CITIES=London
      - HTTPPROXY=on
      - WIREGUARD_PRIVATE_KEY
      - WIREGUARD_ADDRESSES
